config/routes.rb
Rails.application.routes.draw do
  resources :links
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	root 'links#index'

  get 'tags/:tag', to: 'links#index', as: :tag

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
	acts_as_taggable


def self.search(search)
  if search
    where('link_url LIKE ?', "%#{search}%")
  else
  	Link.all
  end
end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
   helper_method :sort_column, :sort_direction

  
  # GET /links
  # GET /links.json
   def index
    if params[:tag]
      @links = Link.tagged_with(params[:tag]).order(sort_column + " " + sort_direction).paginate(:per_page => 5, :page => params[:page])
    else
      @links = Link.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 5, :page => params[:page])
    end
    render action: :index, layout: request.xhr? == nil

    
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:link_url, :subject,:tag_list)
    end

  
    def sort_column
      Link.column_names.append('name').include?(params[:sort]) ? params[:sort] : "link_url"
    end
  
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	


def sortable(column, title = nil)
  title ||= column.titleize
  css_class = column == sort_column ? "current #{sort_direction}" : nil
  direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
  link_to title, {:sort => column, :direction => direction}, {:class => css_class}
end




end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LinkApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/links/_form.html.erb
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= form_with(model: link, local: true) do |form| %>
  <div class="input-group">
    <span  id="basic-addon1">
      <i  aria-hidden="true"></i></span>
      <%= form.text_field :link_url, id: :link_link_url,:class => "form-control",:placeholder => "Link Url" %>
  </div>
  <div class="input-group">
    <span  id="basic-addon2">
        <i  aria-hidden="true"></i></span>
          <%= form.text_field :subject, id: :subject,:class => "form-control",:placeholder => "Link Subject" %>  
  </div>
  <div class="input-group">
    <span  id="basic-addon2">
        <i  aria-hidden="true"></i></span>
          <%= form.text_field :tag_list, id: :tag_list,:class => "form-control",:placeholder => "Add , separeated Tags" %>  
  </div>
  <div>
    <%= form.submit "Submit",:class => "btn btn-success btn-submit" %>
  </div>
<%end%>

app/views/links/_links.html.erb
  <thead>
        <tr>
            <th><%= sortable "link_url"%></th>
            <th><%= sortable "subject"%></th>
            <th><%= sortable "tags"%></th>
            <th colspan="3"></th>
        </tr>
    </thead>
    <tbody>
        <% @links.each do |link| %>
      <tr>
        <td><%= link.link_url %></td>
        <td><%= link.subject %></td>
        <td><%= raw(link.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')) %></td>
        <td><%= link_to 'Show', link %></td>
        <td><%= link_to 'Edit', edit_link_path(link) %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    
    </tbody>
   
       <%= hidden_field_tag :direction, params[:direction] %>
       <%= hidden_field_tag :sort, params[:sort] %>

app/views/links/edit.html.erb
<!-- Bootstrap code -->
<!DOCTYPE html>
<html>
<head>
  <title>Flat Admin V.3 - Free flat-design bootstrap administrator templates</title>
  
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" type="text/css" href="../assets/css/vendor.css">
  <link rel="stylesheet" type="text/css" href="../assets/css/flat-admin.css">

  <!-- Theme -->
  <link rel="stylesheet" type="text/css" href="../assets/css/theme/blue-sky.css">
  <link rel="stylesheet" type="text/css" href="../assets/css/theme/blue.css">
  <link rel="stylesheet" type="text/css" href="../assets/css/theme/red.css">
  <link rel="stylesheet" type="text/css" href="../assets/css/theme/yellow.css">

</head>
<body>
<div class="app app-default">

<%= render 'shared/sidebar' %>

<script type="text/ng-template" id="sidebar-dropdown.tpl.html">
  <div class="dropdown-background">
    <div class="bg"></div>
  </div>
  <div class="dropdown-container">
    {{list}}
  </div>
</script>

<%= render 'shared/nav_bar' %>
 <div class="row">

<div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <b> Edit the Link </b>
        </div> 
        <div class="card-body">
          <div class="row">
  					<div class="col-md-6">
          		<%= render 'form', link: @link %>
        		</div>
      		</div>
    		</div>
  		</div>
</div>
 </div>
 </div>
  <script type="text/javascript" src="../assets/js/vendor.js"></script>
  <script type="text/javascript" src="../assets/js/app.js"></script>

</body>
</html>

app/views/links/index.html.erb
<!-- Bootstrap code -->
<!DOCTYPE html>
<html>
<head>
  <title>Flat Admin V.3 - Free flat-design bootstrap administrator templates</title>
  
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" type="text/css" href="../assets/css/vendor.css">
  <link rel="stylesheet" type="text/css" href="../assets/css/flat-admin.css">

  <!-- Theme -->
  <link rel="stylesheet" type="text/css" href="../assets/css/theme/blue-sky.css">
  <link rel="stylesheet" type="text/css" href="../assets/css/theme/blue.css">
  <link rel="stylesheet" type="text/css" href="../assets/css/theme/red.css">
  <link rel="stylesheet" type="text/css" href="../assets/css/theme/yellow.css">

</head>
<body>
  <div class="app app-default">

<%= render 'shared/sidebar' %>

<script type="text/ng-template" id="sidebar-dropdown.tpl.html">
  <div class="dropdown-background">
    <div class="bg"></div>
  </div>
  <div class="dropdown-container">
    {{list}}
  </div>
</script>

<%= render 'shared/nav_bar' %>

  <div class="row">
    <div class="col-xs-12">
      <div class="card">
       
        <div class="card-body">
          <div class="row">
  
    <div class="col-xs-12">
      <div class="card">
        <div class="card-header navbar-collapse collapse in">
          <div class="navbar-left">
              <b>Stored Links</b>
          </div>
          <div class="navbar-right" style="padding-bottom: 15px;">
              <%= form_tag links_path, :method => 'get', :id => "links_search" do %>
                <%= text_field_tag :search, params[:search], :id => "search", :type => "text", :placeholder => "Search.." %>
                <%= submit_tag "Search", :name => nil,:class => "btn-search" %>
              <%end%>
          </div>
        </div>
        <div class="card-body no-padding">
          <table id = "links" class="datatable table table-striped primary" cellspacing="0" width="100%">
    <%= render 'links'%>
   
    </tbody>
</table>
  <%= will_paginate @products %>
        </div>
      </div>
    </div>
  </div>
</div>

  </div>
  
  <script type="text/javascript" src="../assets/js/vendor.js"></script>
  <script type="text/javascript" src="../assets/js/app.js"></script>

</body>
</html>

app/views/links/index.js.erb
$("#links").html("<%= escape_javascript(render("links")) %>");

app/views/links/new.html.erb
<!-- Bootstrap code -->
<!DOCTYPE html>
<html>
<head>
  <title>Flat Admin V.3 - Free flat-design bootstrap administrator templates</title>
  
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" type="text/css" href="../assets/css/vendor.css">
  <link rel="stylesheet" type="text/css" href="../assets/css/flat-admin.css">

  <!-- Theme -->
  <link rel="stylesheet" type="text/css" href="../assets/css/theme/blue-sky.css">
  <link rel="stylesheet" type="text/css" href="../assets/css/theme/blue.css">
  <link rel="stylesheet" type="text/css" href="../assets/css/theme/red.css">
  <link rel="stylesheet" type="text/css" href="../assets/css/theme/yellow.css">

</head>
<body>
<div class="app app-default">

<%= render 'shared/sidebar' %>

<script type="text/ng-template" id="sidebar-dropdown.tpl.html">
  <div class="dropdown-background">
    <div class="bg"></div>
  </div>
  <div class="dropdown-container">
    {{list}}
  </div>
</script>

<%= render 'shared/nav_bar' %>
 <div class="row">

<div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <b>Create New Link </b>
        </div> 
        <div class="card-body">
          <div class="row">
  					<div class="col-md-6">
          		<%= render 'form', link: @link %>
        		</div>
      		</div>
    		</div>
  		</div>
</div>
 </div>
 </div>
  <script type="text/javascript" src="../assets/js/vendor.js"></script>
  <script type="text/javascript" src="../assets/js/app.js"></script>

</body>
</html>

app/views/links/show.html.erb
<!-- Bootstrap code -->
<!DOCTYPE html>
<html>
<head>
  <title>Flat Admin V.3 - Free flat-design bootstrap administrator templates</title>
  
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" type="text/css" href="../assets/css/vendor.css">
  <link rel="stylesheet" type="text/css" href="../assets/css/flat-admin.css">

  <!-- Theme -->
  <link rel="stylesheet" type="text/css" href="../assets/css/theme/blue-sky.css">
  <link rel="stylesheet" type="text/css" href="../assets/css/theme/blue.css">
  <link rel="stylesheet" type="text/css" href="../assets/css/theme/red.css">
  <link rel="stylesheet" type="text/css" href="../assets/css/theme/yellow.css">

</head>
<body>
<div class="app app-default">

<%= render 'shared/sidebar' %>

<script type="text/ng-template" id="sidebar-dropdown.tpl.html">
  <div class="dropdown-background">
    <div class="bg"></div>
  </div>
  <div class="dropdown-container">
    {{list}}
  </div>
</script>

<%= render 'shared/nav_bar' %>
 <div class="row">

<div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <b> Link Deatils </b>
        </div> 
        <div class="card-body">
          <div class="row">
  					<div class="col-md-6">
          	<%= form_with(model: @link, local: true) do |form| %>
  <div class="input-group">
    <span  id="basic-addon1">
      <i  aria-hidden="true"></i></span>
      <%= form.text_field :link_url, id: :link_link_url,:class => "form-control",:placeholder => "Link Url" %>
  </div>
  <div class="input-group">
    <span  id="basic-addon2">
        <i  aria-hidden="true"></i></span>
          <%= form.text_field :subject, id: :subject,:class => "form-control",:placeholder => "Link Subject" %>  
  </div>
  <div class="input-group">
    <span  id="basic-addon2">
        <i  aria-hidden="true"></i></span>
        <% if @link.tags.present?%>
          <%= form.text_field :tag_list, id: :tag_list,:class => "form-control",:value => "#{@link.tags.pluck(:name).join(',')}" %>  
  			<%else%>
  				<%= form.text_field :tag_list, id: :tag_list,:class => "form-control",:value => "No Tag present" %>  
  			<%end%>
  </div>
  <%end%>
        		</div>
      		</div>
    		</div>
  		</div>
</div>
 </div>
 </div>
  <script type="text/javascript" src="../assets/js/vendor.js"></script>
  <script type="text/javascript" src="../assets/js/app.js"></script>

</body>
</html>

app/views/shared/_nav_bar.html.erb
<div class="app-container">

  <nav class="navbar navbar-default" id="navbar">
  <div class="container-fluid">
    <div class="navbar-collapse collapse in">
      <ul class="nav navbar-nav navbar-mobile">
        <li>
          <button type="button" class="sidebar-toggle">
            <i class="fa fa-bars"></i>
          </button>
        </li>
        <li class="logo">
          <a class="navbar-brand" href="#"><span class="highlight">Flat v3</span> Admin</a>
        </li>
        <li>
          <button type="button" class="navbar-toggle">
            <img class="profile-img" src="../assets/images/profile.png">
          </button>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-left">
        <li class="navbar-title"><span class="highlight">DEMO APP</span></li>
        <li class="navbar-search hidden-sm">
        
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown profile">
          
            <img class="profile-img" src="../app/assets/imagesassets/images/profile.png">
            <div class="title">Profile</div>
          
          <div class="dropdown-menu">
            <div class="profile-info">
              <h4 class="username"><%=current_user.email%></h4>
            </div>
            <ul class="action">
              <li>
                <a href="<%=edit_user_registration_path(current_user)%>">
                  Profile
                </a>
              </li>
              <li>
                <a href="<%=registration_path(current_user)%>"" data-method="delete">
                  Delete My Account
                </a>
              </li>
              <li>
                <a href="<%=destroy_user_session_path%>" data-method="delete">
                  Logout
                </a>
              </li>
            </ul>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_sidebar.html.erb
<aside class="app-sidebar" id="sidebar">
  <div class="sidebar-header">
    <button type="button" class="sidebar-toggle">
      <i class="fa fa-times"></i>
    </button>
  </div>
  <div class="sidebar-menu">
    <ul class="sidebar-nav">
      <li class="">
        <a href="<%=links_path%>">
          <div class="icon">
            <i class="fa fa-tasks" aria-hidden="true"></i>
          </div>
          <div class="title">ALL Links</div>
        </a>
      </li>
      <li class="@@menu.messaging">
        <a href="<%=new_link_path%>">
          <div class="icon">
            <i class="fa fa-comments" aria-hidden="true"></i>
          </div>
          <div class="title"> New Link</div>
        </a>
      </li>
      <li class="dropdown active">
      <a href="<%=links_path%>">
          <div class="icon">
            <i class="fa fa-cube" aria-hidden="true"></i>
          </div>
          <div class="title">Back</div>
          </a>
      </li>
    </ul>
  </div>
  <div class="sidebar-footer">
    <ul class="menu">
      <li>
        <a href="/" class="dropdown-toggle" data-toggle="dropdown">
          <i class="fa fa-cogs" aria-hidden="true"></i>
        </a>
      </li>
      <li><a href="#"><span class="flag-icon flag-icon-th flag-icon-squared"></span></a></li>
    </ul>
  </div>
</aside>